config/routes.rb
ISeekiGive::Application.routes.draw do

  match 'profile/photos' => 'profile#photos', :as => :profile_photos
  match 'profile/your-keywords-tags' => 'profile#your_keywords_tags', :as => :your_keywords_tags
  match 'profile/experience-and-education' => 'profile#experience_and_education', :as => :experience_and_education
  match 'profile' => 'profile#index', :as => :profile
  match 'profile/photos/crop' => 'profile#crop_profile_photo'
  match 'profile/cover_photo/crop' => 'profile#crop_cover_photo'  
  match 'dashboard' => 'dashboard#index', :as => :dashboard

  resources :phone_numbers
  match 'user_tags' => 'tags#get_user_tags'

  match 'search-users' => 'public#get_all_users_with_tags'
  
  match 'account-settings' => 'accounts#settings', :as => :account_settings

  resources :educations
  resources :skills
  resources :tags
  resources :experiences
  resources :password_resets
  resources :languages, :only => [:create, :destroy]
  
  resources :sessions

  resources :connections, :only => [:new] do
    collection do
      get :callback
    end
  end

  resources :users do
    member do
      get  :activate
      get  :resend_confirmation
      get  :public_profile
      get  :display_calendar
      post :create_schedule
    end
  end

  resources :perspectives do
    member do
      get :save
    end
    collection do
      get :good
      get :bad
      get :ugly
    end
  end

  match 'locations'      => "public#locations"

  match 'popup' => 'users#popup', :as => :popup

  match "oauth/:provider/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  get "oauths/oauth"
  get "oauths/callback"

  match 'logout'  => 'sessions#destroy',  :as => :logout
  match 'login'   => 'sessions#new',      :as => :login
  match 'signup'  => 'public#signup',         :as => :signup

  post 'email_checker'      => 'users#email_checker',      :as => 'email_checker'
  
  match 'terms-of-service'  => 'public#terms_of_service',  :as => :terms_of_service
  match 'privacy-policy'    => 'public#privacy_policy',    :as => :privacy_policy
  match 'about-us'          => 'public#about_us',          :as => :about_us
  match 'how-it-works'      => 'public#how_it_works',      :as => :how_it_works

  root :to => 'public#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_login

  def index
    @user = current_user
  end
end

app/views/dashboard/_breadcrumb.html.erb
<div class="row breadcrumb-container">
  <div class="span12">
    <ul class="breadcrumb">
      <% if current_page?(dashboard_path) %>
        <li class="active">
          Dashboard
        </li>
      <% elsif current_page?(profile_path) %>
        <li>
          <%= link_to "Dashboard", dashboard_path %>
          <span class="divider">></span>
        </li>
        <li class="active">
          Profile
        </li>
      <% elsif current_page?(perspectives_path) %>
        <li>
          <%= link_to "Dashboard", dashboard_path %>
          <span class="divider">></span>
        </li>
        <li class="active">
          Perspectives
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/dashboard/_navigation.html.erb
<div class="container">
  <div class="row">
    <div class="span10">
      <nav class="dashboard" role="navigation">
        <div class="navbar-collapse navbar-ex1-collapse">
          <ul class="nav nav-pills">
            <%= nav_link "Dashboard", dashboard_path %>
            <%= nav_link "Profile", profile_path, ApplicationHelper::NAV["profile"] %>
            <%= nav_link "Perspectives", perspectives_path %>
            <%= nav_link "Sessions", 'javascript:void(0)' %>
            <%= nav_link "Boosters", 'javascript:void(0)' %>

            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">Account<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <%= nav_link "Notifications", "javascript:void(0);" %>
                <%= nav_link "Payout Preferences", "javascript:void(0);" %>
                <%= nav_link "Transaction History", "javascript:void(0);" %>
                <%= nav_link "Settings", account_settings_path %>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>
    </div>
    <div class="span2" style="padding-top:6px;">
      <% if controller.controller_name == "profile" %>
        <%= link_to public_profile_user_path(@user), :class => "btn btn-default", :target => "_blank" do %>
          <i class="icon-eye-open"></i>
          View Profile
        <% end %>
      <% end %>
    </div>
  </div>
  <hr class="dashboard-nav-hr"/>
<%#= render "breadcrumb" %>
</div>

app/views/dashboard/_profile_side_nav.html.erb
<aside class="sidebar-left">
  <ul class="nav nav-pills nav-stacked nav-arrow">
    <%= nav_link "Edit Profile", profile_path %>
    <%= nav_link "Photos", "" %>
    <%= nav_link "Experience and Education", experience_and_education_path %>
    <%= nav_link "Your Keywords Tags", "" %>
    <%= nav_link "Trust and Verification", "" %>
    <%= nav_link "Reviews", "" %>
  </ul>
</aside>

app/views/dashboard/index.html.erb
<%=h content_for(:title, "| Dashboard") %>

<%= render "navigation" %>

<div class="gap gap-small"></div>

<div class="container">
  <div class="row">
    <div class="span4 offset2">
      <%= link_to profile_path, :class => "hover-img" do %>
        <%= image_tag("new-wave/going_out_tonight_800x600.jpg") %>
        <h5 class="hover-title-bottom-left hover-hold black-back">Profile</h5>
        <div class="hover-inner">
          <p>
            Tell us about yourself. Completed profiles help us match the relevance of Seeker
            - Giver experiences and interests.
          </p>
        </div>
      <% end %>
    </div>
    <div class="span4">
      <%= link_to perspectives_path, :class => "hover-img" do %>
        <%= image_tag("new-wave/in_the_bokeh_forest_800x600.jpg") %>
        <h5 class="hover-title-bottom-left hover-hold black-back">PERSPECTIVE</h5>
        <div class="hover-inner">
          <p>
            Read or Share stories of "The Good, The Bad and The Ugly".
            Keep track of your stats and Perspectives from others you've saved.
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <div class="gap gap-small"></div>

  <div class="row">
    <div class="span4 offset2">
      <%= link_to "javascript:;", :class => "hover-img" do %>
        <%= image_tag("new-wave/a_dreamy_jump_800x600.jpg") %>
        <h5 class="hover-title-bottom-left hover-hold black-back">SESSION</h5>
        <i class="icon-lock hover-icon hover-hold icon-5x"></i>
        <div class="hover-inner">
          <p>
            Exchange your free time for rewards and make yourself available to chat with a relevant Seeker.
            Manage schedules, sessions and rewards here.
          </p>
        </div>
      <% end %>
    </div>
    <div class="span4">
      <%= link_to "javascript:;", :class => "hover-img" do %>
        <%= image_tag("new-wave/the_hidden_power_of_the_heart_800x600.jpg") %>
        <h5 class="hover-title-bottom-left hover-hold black-back">BOOSTER</h5>
        <div class="hover-inner">
          <p>
            Start a campaign and raise proceeds for a cause you care about.
            Easily invite others to share their time and give back to support your campaign.
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="gap"></div>

app/views/dashboard/profile.html.erb
<%=h content_for(:title, "| Profile") %>

<%= render "navigation" %>

<%= render "shared/confirmation_notice" %>

<div class="gap gap-small"></div>

<div class="container">
  <div class="row">
    <div class="span3">
      <%= render "profile_side_nav" %>
    </div>
    <div class="span9">
      <%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
        <fieldset>
          <div class="control-group">
            <%= f.label :display_name, :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :display_name, :class => "span3" %>
              <div class="field-notice">
                This is the name that will display on your public profile and posts.
              </div>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :first_name, :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :first_name, :class => "span3" %>
              <div class="field-notice">
                This is only shared once your have a confirmed Session with another iSeekiGive user.
              </div>
            </div>
          </div>
          <div class="control-group">
            <%= f.label :last_name, :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :last_name, :class => "span3" %>
              <div class="field-notice">
                This is only shared once your have a confirmed Session with another iSeekiGive user.
              </div>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :gender, :class => "control-label" %>
            <div class="controls span6">
              <%= f.select :gender, ["male", "female"], :class => "span3" %>
              <div class="field-notice">
                We use this data for analysis and never share it with other users.
              </div>
            </div>
            <div class="span2 right">
              <span class="label">
                Private
                <i class="icon-lock"></i>
              </span>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :date_of_birth, :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :date_of_birth, :value => @user.date_of_birth.strftime("%m/%d/%Y"), :class => "span3", :"data-datepicker" => "datepicker" %>
              <div class="field-notice">
                We use this data for analysis and never share it with other users.
              </div>
            </div>
            <div class="span2 right">
              <span class="label">
                Private
                <i class="icon-lock"></i>
              </span>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :email, "Email Address", :class => "control-label" %>
            <div class="controls span6">
              <% if @user.external? %>
                <%= f.text_field :email, :class => "span3", :readonly => true %>
              <% else %>
                <%= f.text_field :email, :class => "span3" %>
              <% end %>
              <div class="field-notice">
                This is only shared once your have a confirmed Session with another iSeekiGive user.
              </div>
            </div>
            <div class="span2 right">
              <span class="label">
                Private
                <i class="icon-lock"></i>
              </span>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :location, "Where You Live", :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :location, :class => "span3" %>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :other_locations, "Places you've lived before", :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_field :other_locations, :class => "span3" %>
              <div class="field-notice">
                Many Seekers are considering relocations, new cities and countries.<br/>
                If you've lived in other cities, this will help increase relevant matching
                of your experiences and perspectives.
              </div>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :descriptions, "Describe Yourself", :class => "control-label" %>
            <div class="controls span6">
              <%= f.text_area :descriptions, :class => "span3", :rows => 5 %>
              <div class="field-notice">
                iSeekiGive is built on real perspectives for life transitions.<br/>
                Help other people get to know you better.<br/>
                What brings you to iSeekiGive?<br/>
                Tell them about yourself and any  life transitions you may have had<br/>
                Do you have a life motto or tip(s) for your own life?
              </div>
            </div>
          </div>

          <div class="control-group">
            <%= f.label :descriptions, "Describe Yourself", :class => "control-label" %>
            <div class="controls span6">
              <% @user.languages.each do |l| %>
              <span class="label">
                <%= l.name %>
                <i class="icon-remove"></i>
              </span>
              <% end %>
              <div class="field-notice">
                Add languages you speak.
              </div>
            </div>
          </div>

        </fieldset>
      <% end %>
    </div>
  </div>
</div>