config/routes.rb
ISeekiGive::Application.routes.draw do

  match 'profile/photos' => 'profile#photos', :as => :profile_photos
  match 'profile/your-keywords-tags' => 'profile#your_keywords_tags', :as => :your_keywords_tags
  match 'profile/experience-and-education' => 'profile#experience_and_education', :as => :experience_and_education
  match 'profile' => 'profile#index', :as => :profile
  match 'profile/photos/crop' => 'profile#crop_profile_photo'
  match 'profile/cover_photo/crop' => 'profile#crop_cover_photo'  
  match 'dashboard' => 'dashboard#index', :as => :dashboard

  resources :phone_numbers
  match 'user_tags' => 'tags#get_user_tags'

  match 'search-users' => 'public#get_all_users_with_tags'
  
  match 'account-settings' => 'accounts#settings', :as => :account_settings

  resources :educations
  resources :skills
  resources :tags
  resources :experiences
  resources :password_resets
  resources :languages, :only => [:create, :destroy]
  
  resources :sessions

  resources :connections, :only => [:new] do
    collection do
      get :callback
    end
  end

  resources :users do
    member do
      get  :activate
      get  :resend_confirmation
      get  :public_profile
      get  :display_calendar
      post :create_schedule
    end
  end

  resources :perspectives do
    member do
      get :save
    end
    collection do
      get :good
      get :bad
      get :ugly
    end
  end

  match 'locations'      => "public#locations"

  match 'popup' => 'users#popup', :as => :popup

  match "oauth/:provider/callback" => "oauths#callback"
  match "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  get "oauths/oauth"
  get "oauths/callback"

  match 'logout'  => 'sessions#destroy',  :as => :logout
  match 'login'   => 'sessions#new',      :as => :login
  match 'signup'  => 'public#signup',         :as => :signup

  post 'email_checker'      => 'users#email_checker',      :as => 'email_checker'
  
  match 'terms-of-service'  => 'public#terms_of_service',  :as => :terms_of_service
  match 'privacy-policy'    => 'public#privacy_policy',    :as => :privacy_policy
  match 'about-us'          => 'public#about_us',          :as => :about_us
  match 'how-it-works'      => 'public#how_it_works',      :as => :how_it_works

  root :to => 'public#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/views/shared/_breadcrumb.html.erb
<div class="breadcrumb">
  <li>
    <span></span>
    <%= link_to "DASHBOARD", dashboard_user_path(current_user) %>
  </li>

  <li class="current">
    <span></span>
    <%= link_to "Profile", edit_user_path(current_user) %>
  </li>

  <%= link_to public_profile_user_path(@user), :class => 'btn pull-right eye-button' do %>
    <span class="icon-eye-open"></span> VIEW PROFILE
  <% end %>

</div>

app/views/shared/_buy_points.html.erb
<h4>
  Buy More Points
</h4>
<p>1 USD  = 100 Points</p>
<%= form_tag pay_for_points_seeker_path(current_user) do %>
    <%= label_tag "Amount (USD):" %>
    <%= text_field_tag :amount %>
    <br/>
    <%= submit_tag 'Buy' %>
<% end %>

app/views/shared/_confirmation_notice.html.erb
<% unless current_user.activated? %>
  <div class="container">
    <div class="row">
      <div class="span12">
        <div class="alert fade in alert-success">
          <button class="close" data-dismiss="alert">×</button>
          Confirmation email sent to you.
          (<%= link_to "send email again", resend_confirmation_user_path(current_user.id) %>)
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_dashboard_popup.html.erb
<a class="modal_popup" href="#modal_content"></a>

<div style="display:none">
  <div id="modal_content">
    <p class="lead well">
      Welcome to iSeekiGive,
      We hope you’ll find inspiration, knowledge and rewards.
      <br/><br/>
      iSeekiGive’s Dashboard provides a bird’s-eye view of your profile, access level, rewards and activity.     
      <br/>
      <br/>
      <a href='javascript:void(0)' class="btn btn-primary">Next Step >> </a>

      <%= link_to "Go to Dashboard", popup_path(:con => controller.controller_name, :act => controller.action_name), :class => "btn btn-primary close-popup pull-right", :remote => true %>
    </p>
  </div>
</div>

app/views/shared/_demo_header.html.erb
<header class="main shrink" style="padding: 0">
<div class="container">
<div class="row">
<div class="span2" style="margin: 0; padding: 0">
  <div class="span2" style="margin: 0 ; padding: 0">  <%= link_to image_tag('logo.png', :style => "width:142px; height:70px"), root_path,:class => "brand"   %>
  </div>

</div>

<div class="span4" id="search-text" style="margin: 30px 0 0 0;">
  <%= form_tag '#', :method => "get" do %>
      <%= text_field_tag "tag",'',:class => "input-xlarge", :placeholder => "Find givers" %>
  <% end %>
</div>
<div class="span6" style="margin: 25px 0 0 0; margin-left: 100px;">
  <div class="span3 top-menu " >
    <nav class="pull-right">
      <ul class="nav nav-pills flexnav" id="flexnav" data-breakpoint="800">
        <li >
          <%= link_to "How it works", how_it_works_path  %>
        </li>
        <li >
          <%= link_to "About Us", "http://blog.iseekigive.com/ourstory", :target => "_blank"  %>
        </li>
      </ul>
    </nav>
  </div>

  <div class="nav-collapse pull-right" >
    <% if current_user %>
          <ul class="nav">
            <li class="dropdown" id="profile-name">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <i>
                  <%= image_tag(current_user.profile_photo.public_profile, :class=>'img-rounded profile-image') if current_user.profile_photo.present? %>
                </i>
                <%= current_user.name %>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">

                <% if current_user %>

                    <li class="<%= "active" if current_page?(dashboard_user_path(current_user)) %>">
                      <%= link_to "Dashboard", dashboard_user_path(current_user) %>
                    </li>
                    <li class="<%= "active" if current_page?(user_perspectives_path(current_user)) %>">
                      <%= link_to "Perspectives", user_perspectives_path(current_user) %>
                    </li>
                    <li class="<%= "active" if current_page?(user_perspectives_path(current_user)) %>">
                      <%= link_to "Manage Sessions", user_perspectives_path(current_user) %>
                    </li>
                    <li class="<%= "active" if current_page?(user_path(current_user)) %>">
                      <%= link_to "Edit Profile", edit_user_path(current_user) %>
                    </li>
                    <li>
                      <%= link_to "Boosters", "Javascript:;" %>
                    </li>

                <% end %>


                <li class="divider"></li>
                <li>
                  <%= link_to "Logout", logout_path %>
                </li>
              </ul>
            </li>
          </ul>
    <% else %>
        <ul class="nav nav-pills flexnav" id="flexnav" data-breakpoint="800">
          <li >
            <%= link_to "Login", login_path  %>
          </li>
        </ul>
    <% end %>


  </div>



</div>
</div>
</div>
</header>

app/views/shared/_footer.html.erb
<footer class="main center">
  <div class="container">
    <ul class="list list-inline nav-footer">
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "How it works", how_it_works_path %>
      </li>
      <li>
        <%= link_to "About Us", "http://facelift.iseekigive.com/clkn/http/blog.iseekigive.com/ourstory", :target => "_blank" %>
      </li>
      <li>
        <%= link_to "Login", login_path %>
      </li>
    </ul>
    <ul class="list list-inline">
      <li>
        <a href="#" class="icon-facebook box-icon-to-inverse animate-icon-bottom-to-top" data-toggle="tooltip" title="Facebook"></a>
      </li>
      <li>
        <a href="#" class="icon-twitter box-icon-to-inverse animate-icon-bottom-to-top" data-toggle="tooltip" title="Twitter"></a>
      </li>
      <li>
        <a href="#" class="icon-linkedin box-icon-to-inverse animate-icon-bottom-to-top" data-toggle="tooltip" title="Linkedin"></a>
      </li>
      <li>
        <a href="#" class="icon-envelope box-icon-to-inverse animate-icon-bottom-to-top" data-toggle="tooltip" title="Mail"></a>
      </li>
    </ul>
    <div class="gap gap-small"></div>	
    <small>
      Copyright &copy; 2013
      <%= link_to "iSeekiGive Ltd", root_url %>
      . All Rights Reserved.
    </small>
  </div>
</footer>

app/views/shared/_giver_dashboard_menu.html.erb
<div class="row-fluid">
  <%= link_to "Profile", current_user %> |

  <%= link_to "Perspectives", giver_perspectives_path(current_user) %> |

  <%= link_to "Rewards", 'javascript:void(0)' %> |

  <% if current_user.level == 2 %>
    <%= link_to "Sessions", giver_sessions_path(current_user) %> |
  <% else %>
    <%= link_to "Sessions", 'javascript:void(0)' %> |
  <% end %>

  <%= link_to "Boosters", 'javascript:void(0)' %>
</div>

app/views/shared/_header.html.erb
<header class="main shrink">
  <div class="container">
    <div class="row">
      <div class="span2">
        <div class="logo-container">
          <%= link_to image_tag("logo.png"), root_path, :class => "logo" %>
        </div>
      </div>
      <div class="<%= logged_in? ? "span6" : "span7" %>">
        <div class="row">
          <%= form_tag '#', :method => "get", :class => "find-givers-form" do %>
            <i class="icon-search"></i>
            <%= text_field_tag "search_keywords", '' ,:class => "span3", :placeholder => "Find Givers" %>
          <% end %>
        </div>
      </div>
      <div class="<%= logged_in? ? "span4 offset1" : "span3" %>">
        <div class="flexnav-menu-button" id="flexnav-menu-button">Menu</div>
        <nav>
          <ul class="nav nav-pills flexnav" id="flexnav" data-breakpoint="800">
            <%= nav_link "How it works", how_it_works_path %>
            <li>
              <%= link_to "About Us", "http://facelift.iseekigive.com/clkn/http/blog.iseekigive.com/ourstory", :target => "_blank" %>
            </li>
            <% if logged_in? %>
              <li>
                <%= link_to "javascript:;" do %>
                  <i class="icon-box">
                    <%= image_tag(profile_photo_path(current_user, {:width => 25, :height => 25, :version => :icon}), :class=>'img-rounded profile-image') %>
                  </i>
                  <%= current_user.display_name %>
                <% end %>
                <ul>
                  <%= nav_link "Dashboard", dashboard_path %>
                  <%= nav_link "Perspectivs", perspectives_path %>
                  <%= nav_link "Manage Sessions", "javascript:;" %>
                  <%= nav_link "Edit Profile", profile_path %>
                  <%= nav_link "Boosters", "javascript:;" %>
                  <%= nav_link "Logout", logout_path %>
                </ul>
              </li>
            <% else %>
              <%= nav_link "Login", login_path %>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/shared/_personal_details.html.erb
<h4>
  Personal Details:
</h4>
<div class="row-fluid">
  <%= form_tag url do %>
      <div>
        Sessions are generally conducted via Skype. If you prefer another method, please select from below
      </div>
      <%= select_tag(:session_method, options_for_select([['Skype Id', 1], ['Phone number', 2], ['Other', 3]], user.session_method), {:class => 'session-method'}) %>
      <ul class="session-methods">
        <li class="session-method-1"><%= text_field_tag :skype_id, user.skype_id %></li>
        <li class="session-method-2"><%= text_field_tag :contact_number, user.contact_number %></li>
        <li class="session-method-3"><%= text_field_tag :other_contact_details, user.other_contact_details %></li>
      </ul>
      <div>
        <%= label_tag "Select your time zone" %>
      </div>
      <%= time_zone_select(:user_time_zone, :time_zone,nil, :default => (user.user_time_zone if user.user_time_zone.present?) ) %>


      <br/>
      <%= submit_tag 'Update', :class => "btn btn-primary"  %>
  <% end %>
</div>

app/views/shared/_perspectives_popup.html.erb
<a class="modal_popup" href="#modal_content"></a>

<div style="display:none">
  <div id="modal_content">
    <p class="lead well">
      Perspectives.
      <br/>
      <br/>
      <a href='javascript:void(0)' class="btn btn-primary close-popup">Okay</a>
      <%= link_to "Do not show again", popup_path(:con => controller.controller_name, :act => controller.action_name), :class => "btn btn-primary close-popup pull-right", :remote => true %>
    </p>
  </div>
</div>

app/views/shared/_profile_popup.html.erb
<a class="modal_popup" href="#modal_content"></a>

<div style="display:none">
  <div id="modal_content">
    <p class="lead well">
      Profiles help users identify relevant and credible perspectives.
      <br/>
      <br/>
      <a href='javascript:void(0)' class="btn btn-primary close-popup">Okay</a>
      <%= link_to "Do not show again", popup_path(:con => controller.controller_name, :act => controller.action_name), :class => "btn btn-primary close-popup pull-right", :remote => true %>
    </p>
  </div>
</div>

app/views/shared/_seeker_dashboard_menu.html.erb
<div class="row-fluid">
  <%= link_to "Profile", current_user %> |

  <%= link_to "Perspectives", seeker_perspectives_path(current_user) %> |

  <%= link_to "Rewards", 'javascript:void(0)' %> |

  <%= link_to "Sessions", seeker_sessions_path(current_user) %> |

  <%= link_to "Boosters", 'javascript:void(0)' %>

</div>

app/views/shared/_stripe-js.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/" %>
<%= javascript_tag "Stripe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';" %>